#Assembly parameters #####################
# The belief threshold to apply to
#    Statements that are made part of the
#    model
belief_threshold: 0.8
# An optional path to specify a grounding
#    map other than INDRA's built-in one
# grounding_map_path: /path/to/gm.csv
##########################################


#PUBMED SEARCH TERMS ######################
## Generic search terms
#search_terms:
#- "search term 1"
#- "search term 2"
## Gene symbol search terms
#search_genes:
#- AKT1
#- EGFR
###########################################


#GMAIL CREDENTIALS ########################
#gmail:
#  user: 
#  password: 
###########################################

#TWITTER CREDENTIALS ######################
#twitter:
#  consumer_token: 
#  consumer_secret: 
#  access_token: 
#  access_secret: 
###########################################

#NDEX CREDENTIALS #########################
#ndex:
#  user: 
#  password: 
#  network: 
###########################################
