belief_threshold: 0.8
#PUBMED SEARCH TERMS ######################
## Generic search terms
#search_terms:
#- "search term 1"
#- "search term 2"
## Gene symbol search terms
#search_genes:
#- AKT1
#- EGFR
###########################################


#GMAIL CREDENTIALS ########################
#gmail:
#  user: 
#  password: 
###########################################

#TWITTER CREDENTIALS ######################
#twitter:
#  consumer_token: 
#  consumer_secret: 
#  access_token: 
#  access_secret: 
###########################################

#NDEX CREDENTIALS #########################
#ndex:
#  user: 
#  password: 
#  network: 
###########################################
