language: python
python:
  - "2.7"
  - "3.5"
before_install:
  - sudo apt-get install graphviz
  - pwd
  - pip install future requests pygraphviz
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      pip install functools32;
    fi
  - git clone https://github.com/sorgerlab/indra.git
script:
  - pwd
  - echo $TRAVIS_BUILD_DIR
  - export PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR/indra
  - python check_references.py
  - python export/relations_graph.py
  - python export/obo.py
